---
title: "semi_20180420_3"
author: "Yutaka Kuroki"
date: "2018年4月16日"
output: 
  html_document: 
    toc: true
    number_section: true
    md_extensions: -ascii_identifiers
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include =FALSE, echo=FALSE, cache = TRUE, message = FALSE, warning = F)
setwd("..")
```


```{r}
library(tidyverse)
library(TDA)
library(lubridate)
library(scatterplot3d)
```

```{r data_import}
data <- read_csv("data/Bloomberg/assets.csv") %>% 
  gather(ticker, price, -Date) %>% 
  mutate(Date = as_date(Date))
```

```{r toyota}
toyota <- data %>% 
  filter(str_detect(.$ticker, "7230")) %>% 
  mutate(ret = log(price) - log(lag(price, 1)),
         price_1 = lag(price, 1),
         price_2 = lag(price, 2),
         price_3 = lag(price, 3),
         price_4 = lag(price, 4),
         ret_1 = lag(ret, 1),
         ret_2 = lag(ret, 2),
         ret_3 = lag(ret, 3),
         ret_4 = lag(ret, 4))
```


# はじめに

去年使った株価データにの位相幾何的な性質を見たい    
TOPIXを構成する約2000銘柄は多すぎるため、とりあえず代表的なトヨタあたりを

```{r toyota_plot, include = T}
toyota %>% 
  ggplot(aes(Date, price))+
  geom_point()+
  geom_line()+
  theme_bw()+
  scale_x_date(date_labels = "%Y")+
  labs(title = "toyota price")

toyota %>% 
  ggplot(aes(Date, ret))+
  geom_line()+
  theme_bw()+
  scale_x_date(date_labels = "%Y")+
  labs(title = "toyota return")
```

# embedding

日時データなので$\tau = 1$ 

price
```{r price_3dplot, include = T}
toyota %>% 
  select(price, price_1, price_2) %>% 
  scatterplot3d(highlight.3d = T)
```

return
```{r return_3dplot, include = T}
toyota %>% 
  select(ret, ret_1, ret_2) %>% 
  scatterplot3d(highlight.3d = T)
```

リターンの方がふわっとしている。    
取引所の営業日が5日間という理由から、埋め込む次元数は$m = 5$とした

## PCAかけてみる

```{r ret_price}
price <- toyota %>% 
  select(price, price_1:price_4)
return <- toyota %>% 
  select(ret, ret_1:ret_4)
```

```{r pc_ret_price}
pc_price <- price %>% 
  drop_na() %>% 
  prcomp() %>% 
  .$x 
pc_return <- return %>% 
  drop_na() %>% 
  prcomp() %>% 
  .$x
```

```{r toyota_pc_3d, include=T}
scatterplot3d(pc_price[,1:3], highlight.3d = T, type = "l")
scatterplot3d(pc_return[,1:3], highlight.3d = T, type = "l")
```

## 

```{r}

```



# maximum persistence

```{r diags}
diags <- data %>% 
  mutate(ret = log(price) - log(lag(price, 1)),
         price_1 = lag(price, 1),
         price_2 = lag(price, 2),
         price_3 = lag(price, 3),
         price_4 = lag(price, 4),
         ret_1 = lag(ret, 1),
         ret_2 = lag(ret, 2),
         ret_3 = lag(ret, 3),
         ret_4 = lag(ret, 4)) %>% 
  drop_na() %>% 
  select(ticker, ret_1:ret_4) %>% 
  group_by(ticker) %>% 
  nest() %>% 
  mutate(diag = map(data, 
                    ~ alphaDiag(.x) %>% 
                      do.call("cbind",.) %>% 
                      as_tibble()))
```

```{r max_diags}
max_diag <- diags %>% 
  select(-data) %>% 
  unnest() %>% 
  filter(!is.infinite(Death)) %>% 
  group_by(ticker, dimension) %>% 
  summarise(max_diag = max(Death - Birth))
```

```{r max_diags_hist, include = T}
max_diag %>% 
  ggplot(aes(max_diag))+
  geom_histogram()+
  theme_bw()+
  facet_wrap(~dimension, scales = "free_x")
```

