---
title: "semi_20180420_2"
author: "Yutaka Kuroki"
date: "2018年4月16日"
output: 
  html_document: 
    toc: true
    number_section: true
    md_extensions: -ascii_identifiers
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include =FALSE, echo=FALSE, cache = TRUE, message = FALSE, warning = F)
setwd("..")
```


```{r}
library(tidyverse)
library(TDA)
library(lubridate)
library(scatterplot3d)
```

# はじめに

mazdaデータに対してTDAやってみる。   
久々に触るデータの復習

# data

例として一つのロボットアームを取り上げる

```{r import_mames}
b.lf <- list.files("data/mazda/before")
a.lf <- list.files("data/mazda/after")
names <- tibble(names = a.lf) %>% 
  semi_join(tibble(b.lf), by=c("names"="b.lf")) %>% 
  .$names
```

```{r import_data}
tmp_b <- tibble(name = names) %>% 
  mutate(data = map(name, 
                    ~ .x %>% 
                      str_c("data/mazda/before/", .) %>% 
                      read_csv(skip = 71, n_max = 5000, col_names = FALSE) %>% 
                      # slice(1:1000 *5) %>% 
                      transmute(dttm = as_datetime(X1),
                                micro = microseconds(as.integer(X2)),
                                value = X3)),
         type = "before")
tmp_a <- tibble(name = names) %>% 
  mutate(data = map(name, 
                    ~ .x %>% 
                      str_c("data/mazda/after/", .) %>% 
                      read_csv(skip = 71, n_max = 5000, col_names = FALSE) %>% 
                      # slice(1:1000 * 5) %>% 
                      transmute(dttm = as_datetime(X1),
                                micro = microseconds(as.integer(X2)),
                                value = X3)),
         type = "after")
data <- bind_rows(tmp_b, tmp_a) %>% 
  unnest() %>% 
  group_by(name, type) %>% 
  arrange(dttm, micro) %>% 
  mutate(index = 1:n()) %>% 
  ungroup()
```


```{r tsplot_example, include = T}
data %>% 
  ggplot(aes(index, value))+
  geom_line()+
  facet_grid(name~type)+
  theme_bw()

```

# TDA

計算量の問題を鑑みて、$\tau =1, m = 6$で埋め込んだ後、PCAで第3主成分までを取り出した。


```{r nest}
nested <- data %>% 
  group_by(name, type) %>% 
  nest() %>% 
  mutate(data = map(data,
                    ~ .x %>% 
                      select(index, y = value) %>% 
                      mutate(y1 = lag(y, 1),
                             y2 = lag(y, 2),
                             y3 = lag(y, 3),
                             y4 = lag(y, 4),
                             y5 = lag(y, 5),
                             y6 = lag(y, 6)))) %>% 
  mutate(pca = map(data,
                   ~ .x %>% 
                     select(-index) %>% 
                     drop_na() %>% 
                     as.matrix() %>% 
                     prcomp),
         rotate = map(pca,
                      ~ .x$x))
```

例として交換前後1系列の3次元プロットを1つずつ示す

```{r scatterplot, include=T}
nested$rotate[[1]][,1:3] %>% 
  scatterplot3d(highlight.3d = T)

nested$rotate[[11]][,1:3] %>% 
  scatterplot3d(highlight.3d =T)
```


## 結果

先ほど三次元プロットに使用したもののPDを示す

```{r diag_nest}
diag_nest <- nested %>% 
  mutate(diagram = map(rotate,
                       ~ .x[,1:3] %>% 
                         apply(2, scale) %>% 
                         alphaDiag() %>% 
                         do.call("cbind", .) %>% 
                         as_tibble() %>% 
                         filter(!is.infinite(Death)) %>% 
                         as.matrix()))



land_nest <- diag_nest %>% 
  mutate(tseq = map(diagram,
                        ~ .x[,"Death"] %>% 
                          max() %>% 
                          seq(0,.,length=500))) %>% 
  mutate(land_1 = map2(diagram, tseq,
                     ~ landscape(.x, dimension = 1, KK = 1, tseq = .y))) %>% 
  mutate(land_2 = map2(diagram, tseq,
                     ~ landscape(.x, dimension = 2, KK = 1, tseq = .y)))
```


```{r PD, include=T}
diag_nest$diagram[[1]] %>% 
  as_tibble() %>% 
  mutate(dimension = as.factor(dimension)) %>% 
  ggplot(aes(Birth, Death, colour = dimension))+
  geom_point()+
  theme_bw()+
  geom_abline()+
  labs(title="before")

diag_nest$diagram[[11]] %>% 
  as_tibble() %>% 
  mutate(dimension = as.factor(dimension)) %>% 
  ggplot(aes(Birth, Death, colour = dimension))+
  geom_point()+
  theme_bw()+
  geom_abline()+
  labs(title="after")
```


landscapeをプロットした   
1, 2次元共に差がありそう

```{r plot_land, include=T}
land_nest %>% 
  group_by(type) %>% 
  select(name, type, tseq, land_1, land_2) %>% 
  unnest() %>% 
  gather(dimension, land, -name, -type, -tseq) %>%  
  ggplot(aes(tseq, land, colour = type))+
  geom_point(alpha=0.3)+
  theme_bw()+
  facet_grid(type~dimension)
```

1次元の方のみをプロットする。

```{r plot_land_1, include=T}
land_nest %>% 
  group_by(type) %>% 
  select(name, type, tseq, land_1, land_2) %>% 
  unnest() %>% 
  gather(dimension, land, -name, -type, -tseq) %>% 
  filter(dimension == "land_1") %>% 
  ggplot(aes(tseq, land, colour = type))+
  geom_point(alpha=0.2)+
  theme_bw()+
  facet_wrap(~type, ncol=1)
```

2次元の方のみをプロットする。

```{r plot_land_2, include=T}
land_nest %>% 
  group_by(type) %>% 
  select(name, type, tseq, land_1, land_2) %>% 
  unnest() %>% 
  gather(dimension, land, -name, -type, -tseq) %>% 
  filter(dimension == "land_2") %>% 
  ggplot(aes(tseq, land, colour = type))+
  geom_point(alpha=0.2)+
  theme_bw()+
  facet_wrap(~type, ncol=1)
```


# 別のアームでもやってみる

```{r other1}
setwd("..")
tmp_b <- tibble(name = names[11:20]) %>% 
  mutate(data = map(name, 
                    ~ .x %>% 
                      str_c("data/mazda/before/", .) %>% 
                      read_csv(skip = 71, n_max = 5000, col_names = FALSE) %>% 
                      # slice(1:1000 *5) %>% 
                      transmute(dttm = as_datetime(X1),
                                micro = microseconds(as.integer(X2)),
                                value = X3)),
         type = "before")
tmp_a <- tibble(name = names[11:20]) %>% 
  mutate(data = map(name, 
                    ~ .x %>% 
                      str_c("data/mazda/after/", .) %>% 
                      read_csv(skip = 71, n_max = 5000, col_names = FALSE) %>% 
                      # slice(1:1000 * 5) %>% 
                      transmute(dttm = as_datetime(X1),
                                micro = microseconds(as.integer(X2)),
                                value = X3)),
         type = "after")
data <- bind_rows(tmp_b, tmp_a) %>% 
  unnest() %>% 
  group_by(name, type) %>% 
  arrange(dttm, micro) %>% 
  mutate(index = 1:n()) %>% 
  ungroup()
nested <- data %>% 
  group_by(name, type) %>% 
  nest() %>% 
  mutate(data = map(data,
                    ~ .x %>% 
                      select(index, y = value) %>% 
                      mutate(y1 = lag(y, 1),
                             y2 = lag(y, 2),
                             y3 = lag(y, 3),
                             y4 = lag(y, 4),
                             y5 = lag(y, 5),
                             y6 = lag(y, 6)))) %>% 
  mutate(pca = map(data,
                   ~ .x %>% 
                     select(-index) %>% 
                     drop_na() %>% 
                     as.matrix() %>% 
                     prcomp),
         rotate = map(pca,
                      ~ .x$x))
land_nest <- nested %>% 
  mutate(diagram = map(rotate,
                       ~ .x[,1:3] %>% 
                         apply(2, scale) %>% 
                         alphaDiag() %>% 
                         do.call("cbind", .) %>% 
                         as_tibble() %>% 
                         filter(!is.infinite(Death)) %>% 
                         as.matrix())) %>% 
  mutate(tseq = map(diagram,
                        ~ .x[,"Death"] %>% 
                          max() %>% 
                          seq(0,.,length=500))) %>% 
  mutate(land_1 = map2(diagram, tseq,
                     ~ landscape(.x, dimension = 1, KK = 1, tseq = .y))) %>% 
  mutate(land_2 = map2(diagram, tseq,
                     ~ landscape(.x, dimension = 2, KK = 1, tseq = .y)))

```

```{r other1_land, include = T}
land_nest %>% 
  group_by(type) %>% 
  select(name, type, tseq, land_1, land_2) %>% 
  unnest() %>% 
  gather(dimension, land, -name, -type, -tseq) %>% 
  filter(dimension == "land_1") %>% 
  ggplot(aes(tseq, land, colour = type))+
  geom_point(alpha=0.2)+
  theme_bw()+
  facet_wrap(~type, ncol=1)+
  labs(title = "dimension_1")
land_nest %>% 
  group_by(type) %>% 
  select(name, type, tseq, land_1, land_2) %>% 
  unnest() %>% 
  gather(dimension, land, -name, -type, -tseq) %>% 
  filter(dimension == "land_2") %>% 
  ggplot(aes(tseq, land, colour = type))+
  geom_point(alpha=0.2)+
  theme_bw()+
  facet_wrap(~type, ncol=1)+
  labs(title = "dimension_2")
```

