---
title: "Untitled"
author: "Yutaka Kuroki"
date: "2018/4/25"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(TDA)
library(lubridate)
library(scatterplot3d)
```

```{r import_mames}
b.lf <- list.files("data/mazda/before")
a.lf <- list.files("data/mazda/after")
names <- tibble(names = a.lf) %>% 
  semi_join(tibble(b.lf), by=c("names"="b.lf")) %>% 
  .$names
```

```{r import_data}
tmp_b <- tibble(name = names) %>% 
  mutate(data = map(name, 
                    ~ .x %>% 
                      str_c("data/mazda/before/", .) %>% 
                      read_csv(skip = 71, n_max = 5000, col_names = FALSE) %>% 
                      # slice(1:1000 *5) %>% 
                      transmute(dttm = as_datetime(X1),
                                micro = microseconds(as.integer(X2)),
                                value = X3)),
         type = "before")
tmp_a <- tibble(name = names) %>% 
  mutate(data = map(name, 
                    ~ .x %>% 
                      str_c("data/mazda/after/", .) %>% 
                      read_csv(skip = 71, n_max = 5000, col_names = FALSE) %>% 
                      # slice(1:1000 * 5) %>% 
                      transmute(dttm = as_datetime(X1),
                                micro = microseconds(as.integer(X2)),
                                value = X3)),
         type = "after")
data <- bind_rows(tmp_b, tmp_a) %>% 
  unnest() %>% 
  group_by(name, type) %>% 
  arrange(dttm, micro) %>% 
  mutate(index = 1:n()) %>% 
  ungroup()
```

```{r nest}
diags <- data %>% 
  group_by(name, type) %>% 
  nest() %>% 
  mutate(data = map(data,
                    ~ .x %>% 
                      select(index, y = value) %>% 
                      mutate(y1 = lag(y, 1),
                             y2 = lag(y, 2),
                             y3 = lag(y, 3),
                             y4 = lag(y, 4),
                             y5 = lag(y, 5),
                             y6 = lag(y, 6)))) %>% 
  mutate(pca = map(data,
                   ~ .x %>% 
                     select(-index) %>% 
                     drop_na() %>% 
                     as.matrix() %>% 
                     prcomp),
         rotate = map(pca,
                      ~ .x$x)) %>% 
  mutate(diagram = map(rotate,
                       ~ .x[,1:3] %>% 
                         apply(2, scale) %>% 
                         alphaDiag() %>% 
                         do.call("cbind", .) %>% 
                         as_tibble() %>% 
                         filter(!is.infinite(Death))
                       )
         )

lands <- diags %>% 
  mutate(tseq = map(diagram,
                        ~ .x[,"Death"] %>% 
                          max() %>% 
                          seq(0,.,length=500))) %>% 
  mutate(land_1 = map2(diagram, tseq,
                     ~ landscape(.x, dimension = 1, KK = 1, tseq = .y))) %>% 
  mutate(land_2 = map2(diagram, tseq,
                     ~ landscape(.x, dimension = 2, KK = 1, tseq = .y)))
```