---
title: "semi_20180427_1"
author: "Yutaka Kuroki"
date: "2018/4/26"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r}
library(tidyverse)
library(TDA)
library(lubridate)
library(scatterplot3d)
```

```{r import_mames}
b.lf <- list.files("data/mazda/before")
a.lf <- list.files("data/mazda/after")
names <- tibble(names = a.lf) %>% 
  semi_join(tibble(b.lf), by=c("names"="b.lf")) %>% 
  .$names
```

```{r import_data}
tmp_b <- tibble(name = names) %>% 
  mutate(data = map(name, 
                    ~ .x %>% 
                      str_c("data/mazda/before/", .) %>% 
                      read_csv(skip = 71, n_max = 5000, col_names = FALSE) %>% 
                      slice(1:1000 *5) %>%
                      transmute(dttm = as_datetime(X1),
                                micro = microseconds(as.integer(X2)),
                                value = X3)
                    ),
         type = "before")
tmp_a <- tibble(name = names) %>% 
  mutate(data = map(name, 
                    ~ .x %>% 
                      str_c("data/mazda/after/", .) %>% 
                      read_csv(skip = 71, n_max = 5000, col_names = FALSE) %>% 
                      # slice(1:1000 * 5) %>% 
                      transmute(dttm = as_datetime(X1),
                                micro = microseconds(as.integer(X2)),
                                value = X3)),
         type = "after")
data <- bind_rows(tmp_b, tmp_a) %>% 
  unnest() %>% 
  group_by(name, type) %>% 
  arrange(dttm, micro) %>% 
  mutate(index = 1:n()) %>% 
  ungroup() %>% 
  mutate(number = as.integer(str_sub(name, start = -5, end=-5)))


```


```{r}
data %>% 
  filter(number == 1) %>% 
  ggplot(aes(index, value))+
  geom_line()+
  theme_bw()+
  facet_grid(name~type, scales="free")
ggsave("./report/fig/ts.png",
       units = "cm",
       width = 6,
       height = 7)
```

```{r}

diags <- data %>% 
  group_by(name, type) %>% 
  nest() %>% 
  mutate(data = map(data,
                    ~ .x %>% 
                      select(index, y = value) %>% 
                      mutate(y1 = lag(y, 1),
                             y2 = lag(y, 2),
                             y3 = lag(y, 3),
                             y4 = lag(y, 4),
                             y5 = lag(y, 5),
                             y6 = lag(y, 6)))) %>% 
  mutate(pca = map(data,
                   ~ .x %>% 
                     select(-index) %>% 
                     drop_na() %>% 
                     as.matrix() %>% 
                     prcomp),
         rotate = map(pca,
                      ~ .x$x)) %>% 
  mutate(diagram = map(rotate,
                       ~ .x[,1:3] %>% 
                         apply(2, scale) %>% 
                         alphaDiag() %>%
                         do.call("cbind", .) %>%
                         as_tibble() %>%
                         filter(!is.infinite(Death))
                       )
         )

```

```{r}
diags %>% 
  slice(1) %>% 
  select(name, diagram) %>% 
  unnest() %>% 
  mutate(dimension = as.factor(dimension)) %>% 
  ggplot(aes(Birth, Death, colour = dimension))+
  geom_point()+
  geom_abline()+
  theme_bw()
ggsave("./report/fig/PD_example.eps",
       units = "cm",
       height = 10,
       width = 20)
```

```{r}
diags$rotate[[1]] [,1:3]%>% apply(2, scale) %>% scatterplot3d(highlight.3d = T)


```

```{r}
a <- as.matrix(diags$diagram[[1]])
tseq <- seq(0,max(a[,3]), length = 1000)
Land <- landscape(a, dimension = 1, KK = 1, tseq)
d <- data.frame(r = tseq,land = Land)
d %>% 
  ggplot(aes(r, land))+
  geom_line()+
  theme_bw()
ggsave("./report/fig/PL_example.eps",
       units = "cm",
       height = 10,
       width = 20)
```

```{r}
a %>% 
  as_tibble() %>% 
  arrange(Birth, Death) %>% 
  group_by(dimension) %>% 
  mutate(index = seq(0,1, length = n())) %>% 
  ggplot(aes(y = index))+
  geom_segment(aes(x = Birth, xend = Death, yend = index))+
  theme_bw()+
  labs(x = "radius")+
  facet_wrap(~dimension)
ggsave("./report/fig/PB_example.eps",
       units = "cm",
       height = 10,
       width = 20)
```

```{r}
diags %>% 
  select(name, type, diagram) %>% 
  unnest() %>% 
  group_by(name, type) %>% 
  summarise(maxper = max(Death - Birth)) %>% 
  ungroup() %>% 
  group_by(type) %>% 
  ggplot(aes(maxper, fill = type, colour=type))+
  geom_histogram(alpha = 0.5, bins = 20)+
  scale_x_continuous(limits = c(0,2))+
  facet_wrap(~type, ncol=1)+
  theme_bw()
  
```

